-- AlterTable
ALTER TABLE `User` ADD COLUMN `bio` VARCHAR(191) NULL,
    ADD COLUMN `specialization` VARCHAR(191) NULL,
    ADD COLUMN `status` ENUM('ACTIVE', 'INACTIVE') NULL DEFAULT 'ACTIVE',
    ADD COLUMN `telp` VARCHAR(191) NULL;
